### ISSUE TITLE
Add feature to Error 404 page M @Baiyi

### ISSUE THREAD

**Issue by chaowang0524** [Arbruiser/BACoN#17]
Add a "back to search" button or is cat picture is clickable to return to search.

**Comment by chaowang0524** [comment]
Add the button to all pages (except the main)

**Comment by Echo-Lian** [comment]
Do I have to show "Error 404 page M" on the page?

**Comment by chaowang0524** [comment]
> Do I have to show "Error 404 page M" on the page?

404 is Page not found so you don't have to put that on the page literally.
